[dependencies]
Option = "rustic/option@0.3.0"
Result = "rustic/result@0.3.0"

[package]
exclude = ["**/*.spec.luau"]
name = "rustic/convert"
realm = "shared"
registry = "https://github.com/solarhorizon/wally-index"
version = "0.3.0"
